version: '2.1'
services:
    worker:
        image: puckel/docker-airflow:1.9.0-2
        restart: always
        ports:
          - 8793:8793
        volumes:
            - ./dags:/usr/local/airflow/dags
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - REDIS_HOST=192.168.1.44
            - REDIS_PORT=6379
            - POSTGRES_HOST=192.168.1.44
            - POSTGRES_PORT=5432
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        command: worker
